## 使用的资源对象
deployment:
  enabled: true

service:
  enabled: true
  type: ClusterIP
  nodePorts:
    - name: http
      port: 80
  ports:
    - name: http
      port: 80

ingress:
  enabled: true
  hostname: example.com
  path: /

configMaps:
  enabled: true
  data: 
    - type: env
      context:
        FOO: BOO
    - type: file
      mountPath: /etc/nginx/nginx.conf
      context:
        nginx.conf: |-
      

secrets:
  enabled: true

rbac:
  enabled: false

persistentVolumeClaims:
  enabled: false

networkPolicies:
  enabled: false

podDisruptionBudgets:
  enabled: false

serviceMonitors:
  enabled: false

antiAffinity: bool
