env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/helm-chart-generate
    binary: ./bin/helm-chart-generate
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"

archives:
  - id: tarball
    format: tar.gz
    files:
      - LICENSE
      - plugin.yaml