# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: %%CHOOSE_ONE_FROM_CHART_CATEGORIES_FILE%%
  licenses: Apache-2.0
apiVersion: v2
appVersion: %%UPSTREAM_PROJECT_VERSION%%
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: %%DESCRIPTION%%
home: https://bitnami.com
icon: https://github.com/yidaqiang/helm-chart-generate/raw/main/logo.png
keywords:
  - %%UPSTREAM_PROJECT_KEYWORD%%
  - %%UPSTREAM_PROJECT_KEYWORD%%
  - ...
maintainers:
  - name: Broadcom, Inc. All Rights Reserved.
    url: https://github.com/bitnami/charts
name: %%CHART_NAME%%
sources:
  - https://github.com/open-hand/dockerfile/tree/master/javabase
  - https://github.com/open-hand/dockerfile/tree/master/frontbase
version: 0.1.0
